### ISSUE TITLE
run error in "./linux.sh" 

### ISSUE THREAD

**Issue by amiltonwong** [shurans/DeepSlidingShape#1]
Hi, @shurans ,

I follow the setup guide, but came accross the following compilation error, any pre-requisite packages to install beforehand?

============================================
root@milton-All-Series:~/DeepSlidingShape/marvin# ./linux.sh 
In file included from dss.hpp:1:0,
                 from marvin.hpp:5155,
                 from marvin.cu:1:
render_3d.hpp:7:23: fatal error: GL/osmesa.h: No such file or directory
 #include <GL/osmesa.h>
                       ^
compilation terminated.

============================================

THX~

**Comment by shurans** [comment]
Currently the code also depend on OSmesa: http://www.mesa3d.org/osmesa.html.

**Comment by amiltonwong** [comment]
Hi, @shurans ,

I follow your suggestion and install the mesa (http://www.mesa3d.org/repository.html) after building it.
However, I came across this issue: login loop problem
http://askubuntu.com/questions/590561/ubuntu-14-04-login-loop-problem

I think the installed mesa package is conflicting against CUDA-7.5 lib in my system.

How can I solve it?

**Comment by zhoufengbuaa** [comment]
Hi, @amiltonwong 
I got the some problem, when I use CUDA, I found OSmesa cannot work, when I remove CUDA and OSmesa is OK back. And I really do not know how to solve this problem. And what is your solution?

**Comment by shurans** [comment]
Hi @amiltonwong and @zhoufengbuaa, 
I removed the Osmesa dependency in the latest commit. Now it should be able to compile without OSmesa.

**Comment by zhoufengbuaa** [comment]
@amiltonwong Did you run the code? Should I compile Marvin first? When I download this code, which one can run without any change? thx
