### ISSUE TITLE
SUNRGBDMeta_tight_Yaw Not Found

### ISSUE THREAD

**Issue by vorale** [shurans/DeepSlidingShape#15]
Hi @shurans,

I am having an issue when running following line in dss_prepareAnchorbox load('./external/SUNRGBDtoolbox/Metadata/SUNRGBDMeta_tight_Yaw.mat');

I also looked inside following url that this file doesn't exist. 

http://dss.cs.princeton.edu/Release/

Could you please help me where I can download this file? Thanks.

**Comment by shurans** [comment]
It is "load('./external/SUNRGBDtoolbox/Metadata/SUNRGBDMeta.mat');" in the code. May be you are using a old version of this code?

**Comment by vorale** [comment]
Thanks. I actually pulled everything from dss.cs.princeton.edu/release. looks like the code there is older than github.
