### ISSUE TITLE
Error in dss_preparelist after running dss_marvin_script(0,100,1,[] ,1,'RPN_NYU',1,[],0,0);

### ISSUE THREAD

**Issue by HKUSTmji** [shurans/DeepSlidingShape#2]
Dear @shurans , 

After following the guideline and running the Matlab command 'dss_marvin_script(0,100,1,[] ,1,'RPN_NYU',1,[],0,0);', I meet an error:

```
Error using load
Unable to read file '/n/fs/modelnet/deepDetect/code/detector_3d/hasorientation': no such file or
directory.
Error in dss_preparelist (line 8)
load('/n/fs/modelnet/deepDetect/code/detector_3d/hasorientation');
Error in dss_marvin_script (line 155)
    [boxfile_traincnn] =
    dss_preparelist('train',NYUonly,opt.proposal_dir,opt.proposal_dir,proposal_only,cls,opt.box_reg,opt.axisAlign,opt.fullbox,opt.BoxperImage,0,0); 
```

However I don't know where to download this folder. Could you please give some hint~

Thanks a lot
Mengqi

**Comment by shurans** [comment]
You don't need to load this file. 
I have updated the code to remove the dependency of that file. Thanks.

**Comment by brentsony** [comment]
But detector_3d is still required by mRecall.

(And getboxdistribution, genPCindexList, and compute_targetboxdiff). 

Doesn't mRecall get called by detection?
