### ISSUE TITLE
precomputed regoin proposal failure

### ISSUE THREAD

**Issue by zhusj** [shurans/DeepSlidingShape#3]
Hi @shurans ,

It seems that downloading precomputed regoin proposal for NYU and SUNRGBD dataset by running  script: downloadData('../image','http://dss.cs.princeton.edu/Release/sunrgbd_dss_data/','.tensor') failed becasue of Error 404. Could you check if that's the correct URL? Thank you.

**Comment by shurans** [comment]
try downloadData('../sunrgbd_dss_data','http://dss.cs.princeton.edu/Release/sunrgbd_dss_data/','.bin'); instead.
