### ISSUE TITLE
error on reading sunRGBD data

### ISSUE THREAD

**Issue by ph81323** [shurans/DeepSlidingShape#6]
Hi @shurans , 
When I loaded SUNRGBDMetadata.mat in dss_prepareAnchor(),I found that it recorded the paths of depth and rgb image. But I can't find any png data in the directory. Do we need to download the data from the original SUNDRGBD website? or the .bin file in "sunrgbd_dss_data/SUNRGBD/kv1/NYUdata/*.bin" are datasets?
If yes, what is the information in .bin file? How can we convert them to depth and rgb images?

Thanks a lot!

**Comment by shurans** [comment]
The original png data you can download from original SUNRGB-D web set. The *.bin's are prepossessed data to accelerate TSDF calculation. You can reference load() function is dss.hpp to understand how the data is stored.

**Comment by zhoufengbuaa** [comment]
did you run this code success? I found there are lots of error when running RPN_extract() @ph81323

**Comment by neouyghur** [comment]
@zhoufengbuaa  did you run it? could we discuss it together, I am also trying to run this code. But the documentation is not so helpful.

**Comment by ph81323** [comment]
@zhoufengbuaa sorry for the late response. I can't run it successfully neither . I am now stuck in that I don't see the file cls_socre_x.tensor. Does anyone find it?

**Comment by neouyghur** [comment]
@zhoufengbuaa @ph81323 Now, I can run the code. I tested the "dss_marvin_script(0,100,1,[]  ,1,'RPN_NYU',1,[],0,0);". It was running successfully. I think this command is for training the network. @shurans am I a correct?  Now my question is how can I test the network? like I give a 3D scene to the network, it returns me segmentation and detection results. Thank you.

**Comment by ph81323** [comment]
hi, @neouyghur Could you please tell me where the fc6.tensor is? When I run "dss_marvin_script", it said it can't find fc6.tensor and I can't find a folder called "featuremat".

**Comment by neouyghur** [comment]
@ph81323   I can't find the fc6.tensor neither. Although I can run the script, I stop it in the middle. I think this script is for training the network. Am I correct?  When encounter the problem ? In the beginning or in the end of the running? I think this is helping #12. The featuremat folder is created by the code.
