### ISSUE TITLE
file list format

### ISSUE THREAD

**Issue by lidong04** [shurans/DeepSlidingShape#7]
Hi, it seems that the file_list of the 3D scenes is missing.. could you please provide an example of file_list (such as RPN_NYU.list, defined in RPNDataLayer of DSSopt_RPN_extractfea_po.json)? Thanks.

**Comment by shurans** [comment]
You can use the function "dss_RPNpreparelist.m" to generate the list.

**Comment by lidong04** [comment]
Got it, I also figured it out from SUNRGBDMeta.mat:) Thanks!
