### ISSUE TITLE
what kind of version does the system need?

### ISSUE THREAD

**Issue by zhoufengbuaa** [shurans/DeepSlidingShape#8]
I use apt-get to install libsomesa6-dev on ubuntu 15.10 with GTX 980ti, but I found the system is not work. So there is any requirement about Mesa3D? Thank you very much

**Comment by shurans** [comment]
I removed the Osmesa dependency in the latest commit.  Now it should be able to compile without OSmesa. Thanks.

**Comment by zhoufengbuaa** [comment]
Thanks again.
