### ISSUE TITLE
Missing RPN_NYU_train.list

### ISSUE THREAD

**Issue by MarryAnders** [shurans/DeepSlidingShape#9]
Hi @shurans,

In DSSopt_RPN.json, you use **RPN_NYU_train.list** and **RPN_NYU_test.list**. However, it does not exist in http://dss.cs.princeton.edu/Release folder. Where can we find **RPN_NYU_train.list** and **RPN_NYU_test.list** files?

Thx

**Comment by shurans** [comment]
You can use the function "dss_RPNpreparelist.m" to generate the list, and I also add example files in the update.

**Comment by MarryAnders** [comment]
readTensor_v2 does not exist as well

**Comment by shurans** [comment]
It is in DeepSlidingShape/matlab_code/marvin_helper/
